on: [push]
name: Linux_Container_Workflow

env:
  BASE_REPOSITORY: openjdk8alpine
  REPOSITORY: sampleapp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: actions/checkout@v2
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
             
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: az acr repository show-tags -n testtthcontainer --repository sampleapp --top 1 --orderby time_desc
      
      
    - run: |
        docker build --build-arg LOGIN_SERVER=${{ secrets.REGISTRY_LOGIN_SERVER }} --build-arg REPOSITORY=$REPOSITORY --build-arg TAG=$AZURETAG . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$REPOSITORY:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$REPOSITORY:${{ github.sha }}
